###############################################################################
# sim_hists.py is a script to histogram data that is stored in text files 
# and generated by mymain02.py
#
# Author: Thomas McDowell
# Date: 17/12/2020
# Status: In progress
###############################################################################

# Libraries used
import numpy as np
import math
from matplotlib import pyplot as plt
import csv

pi_max_pT_vals_cut1 = []
pi_max_pT_vals_cut2 = []
pi_max_pT_vals_cut3 = []

pi_min_pT_vals_cut1 = []
pi_min_pT_vals_cut2 = []
pi_min_pT_vals_cut3 = []

pi_max_abs_eta_cut1 = []
pi_max_abs_eta_cut2 = []
pi_max_abs_eta_cut3 = []

event_inv_masses = []
K0s_inv_masses = []

with open( 'invmass_eff_err.csv' ) as invmass_file:
	readCSV = csv.reader( invmass_file, delimiter = ',' )
	for row in invmass_file:
		row_list = row.split(',')
		event_inv_masses.append( float( row_list[0] ) )

with open( 'min_max_cut1.csv' ) as cut1_file:
	readCSV = csv.reader( cut1_file, delimiter = ',' )
	for row in cut1_file:
		row_list = row.split(',')
		pi_min_pT_vals_cut1.append( float( row_list[0] ) )
		pi_max_pT_vals_cut1.append( float( row_list[1] ) )
		pi_max_abs_eta_cut1.append( float( row_list[2] ) )

with open( 'min_max_cut2.csv' ) as cut2_file:
        readCSV = csv.reader( cut2_file, delimiter = ',' )
        for row in cut2_file:
                row_list = row.split(',')
                pi_min_pT_vals_cut2.append( float( row_list[0] ) )
                pi_max_pT_vals_cut2.append( float( row_list[1] ) )
                pi_max_abs_eta_cut2.append( float( row_list[2] ) )

with open( 'min_max_cut3.csv' ) as cut3_file:
        readCSV = csv.reader( cut3_file, delimiter = ',' )
        for row in cut3_file:
                row_list = row.split(',')
                pi_min_pT_vals_cut3.append( float( row_list[0] ) )
                pi_max_pT_vals_cut3.append( float( row_list[1] ) )
                pi_max_abs_eta_cut3.append( float( row_list[2] ) )

with open( 'K0s_inv_masses.csv' ) as K0s_masses:
	readCSV = csv.reader( K0s_masses, delimiter = ',' )
	for row in K0s_masses:
		K0s_inv_masses.append( float( row ) )

# pyplot histograms
plt.figure(0)

histbins = [ 0.00, 0.10, 0.15, 0.20, 0.25, 0.30, 0.35, 0.40, 0.45, 0.50,
             0.55, 0.60, 0.65, 0.70, 0.75, 0.80, 0.85, 0.90, 0.95, 1.00,
             1.05, 1.10, 1.15, 1.20, 1.25, 1.30, 1.35, 1.40, 1.45, 1.50,
             1.55, 1.60, 1.65, 1.70, 1.75, 1.80, 2.00 ]


# print( "length of histbins = " + str( len( histbins ) ) )

pi_max_pT_hist = plt.subplot( 3, 1, 1 )
pi_max_pT_hist.set_xlim( 0, 3 )
pi_max_pT_hist.hist(pi_max_pT_vals_cut1, bins = histbins)
pi_max_pT_hist.title.set_text("Max pT of pi+ and pi- in K0K0s Daughter Groups (0.1 GeV cut)")
pi_max_pT_hist.set_xlabel("pT (GeV)")
pi_max_pT_hist.set_ylabel("Number of pi+ and pi-")

pi_min_pT_hist = plt.subplot( 3, 1, 2 )
pi_min_pT_hist.set_xlim( 0, 3 )
pi_min_pT_hist.hist(pi_min_pT_vals_cut1, bins = histbins)
pi_min_pT_hist.title.set_text("Min pT of pi+ and pi- in K0sK0s Daughter Groups (0.1 GeV cut)")
pi_min_pT_hist.set_xlabel("pT (GeV)")
pi_min_pT_hist.set_ylabel("Number of pi+ and pi-")

pi_max_abs_eta_hist = plt.subplot( 3, 1, 3 )
pi_max_abs_eta_hist.hist(pi_max_abs_eta_cut1, bins = 20)
pi_max_abs_eta_hist.title.set_text("Max Abs. Value of eta for pi+ pi- in K0sK0s Daughter Groups (0.5 GeV cut)")
pi_max_abs_eta_hist.set_xlabel("eta")
pi_max_abs_eta_hist.set_ylabel("Number of pi+ and pi-")

plt.show()

plt.figure(1)

pi_max_pT_hist = plt.subplot( 3, 1, 1 )
pi_max_pT_hist.set_xlim( 0, 3 )
pi_max_pT_hist.hist(pi_max_pT_vals_cut2, bins = histbins)
pi_max_pT_hist.title.set_text("Max pT of pi+ and pi- in K0K0s Daughter Groups (0.5 GeV cut)")
pi_max_pT_hist.set_xlabel("pT (GeV)")
pi_max_pT_hist.set_ylabel("Number of pi+ and pi-")

pi_min_pT_hist = plt.subplot( 3, 1, 2 )
pi_min_pT_hist.set_xlim( 0, 3 )
pi_min_pT_hist.hist(pi_min_pT_vals_cut2, bins = histbins)
pi_min_pT_hist.title.set_text("Min pT of pi+ and pi- in K0sK0s Daughter Groups (0.5 GeV cut)")
pi_min_pT_hist.set_xlabel("pT (GeV)")
pi_min_pT_hist.set_ylabel("Number of pi+ and pi-")

pi_max_abs_eta_hist = plt.subplot( 3, 1, 3 )
pi_max_abs_eta_hist.hist(pi_max_abs_eta_cut2, bins = 20)
pi_max_abs_eta_hist.title.set_text("Max Abs. Value of eta for pi+ pi- in K0sK0s Daughter Groups (0.7 GeV cut)")
pi_max_abs_eta_hist.set_xlabel("eta")
pi_max_abs_eta_hist.set_ylabel("Number of pi+ and pi-")

plt.show()

plt.figure(2)

pi_max_pT_hist = plt.subplot( 3, 1, 1 )
pi_max_pT_hist.set_xlim( 0, 3 )
pi_max_pT_hist.hist(pi_max_pT_vals_cut3, bins = histbins)
pi_max_pT_hist.title.set_text("Max pT of pi+ and pi- in K0K0s Daughter Groups (1.0 GeV cut)")
pi_max_pT_hist.set_xlabel("pT (GeV)")
pi_max_pT_hist.set_ylabel("Number of pi+ and pi-")

pi_min_pT_hist = plt.subplot( 3, 1, 2 )
pi_min_pT_hist.set_xlim( 0, 3 )
pi_min_pT_hist.hist(pi_min_pT_vals_cut3, bins = histbins)
pi_min_pT_hist.title.set_text("Min pT of pi+ and pi- in K0sK0s Daughter Groups (1.0 GeV cut)")
pi_min_pT_hist.set_xlabel("pT (GeV)")
pi_min_pT_hist.set_ylabel("Number of pi+ and pi-")

pi_max_abs_eta_hist = plt.subplot( 3, 1, 3 )
pi_max_abs_eta_hist.hist(pi_max_abs_eta_cut3, bins = 20)
pi_max_abs_eta_hist.title.set_text("Max Abs. Value of eta for pi+ pi- in K0sK0s Daughter Groups(1.0 GeV cut)")
pi_max_abs_eta_hist.set_xlabel("eta")
pi_max_abs_eta_hist.set_ylabel("Number of pi+ and pi-")

plt.show()

plt.figure(3)

event_inv_masses_hist = plt.subplot( 2, 1, 1 )
#event_inv_masses_hist.set_xlim( 1.5, 2.5 )
event_inv_masses_hist.hist( event_inv_masses, bins = 100 )
event_inv_masses_hist.title.set_text("Invariant Mass of 4trk Events")
event_inv_masses_hist.set_xlabel("Invariant Mass ()")
event_inv_masses_hist.set_ylabel("No. Events")

# ERROR: something may be broken in calculation for K0s invariant masses,
# so this histogram may be plotting invalid data.
K0s_inv_masses_hist = plt.subplot( 2, 1, 2 )
#K0s_inv_masses_hist.set_xlim( 1.5, 4 )
K0s_inv_masses_hist.hist( K0s_inv_masses, bins = 100 )
K0s_inv_masses_hist.title.set_text("Invariant Mass of K0s")
K0s_inv_masses_hist.set_xlabel("Invariant Mass ()")

plt.show()
